"""Add going_out_bonus column to games table

Revision ID: 222538acd7ec
Revises: ed5880329f23
Create Date: 2026-01-27 09:20:52.208583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '222538acd7ec'
down_revision = 'ed5880329f23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('going_out_bonus', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_column('going_out_bonus')

    # ### end Alembic commands ###
